openshift/image-inspector

pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go
When no authentication configuration are given
make sure that a default empty one is returned.
Fixes #2
=> inspect: add empty auth conf as default

pkg/cmd/types.go, pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go, pkg/openscap/openscap.go, pkg/openscap/openscap_test.go, pkg/util/util.go, pkg/util/util_test.go
These are the candidate patches for the `release-2.0.z` branch to release 2.0.1.
@enoodle @pweil- make sure we're not missing something and we're not introducing regressions. Thanks.
=> Backported patches for 2.0.1

pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go
=> openscap: Warn instead of fail when loading configs

README.md, cmd/image-inspector.go, pkg/cmd/types.go, pkg/cmd/types_test.go, pkg/inspector/image-inspector.go, pkg/openscap/openscap.go, pkg/openscap/types.go
I added an option to display an HTML report for an OpenSCAP scan.  It is served at <serve_path>/api/v1/openscap-report.  
I thought this would be a convenient option.
=> HTML Reporting for OpenSCAP

pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go
An unfortunate oversight on my part.  If a the --openscap-html-report was not set, the image-inspector would attempt to process that file anyway, causing an error.
=> HTML Report error should only be processed if option is true

cmd/image-inspector.go, pkg/cmd/types.go, pkg/inspector/image-inspector.go, pkg/openscap/openscap.go
A proposed fix for #18 
Added a new argument to image-inspector (and to OSCAPScanner) to get an alternative CVE source from the user.
=> Adding CVEURLPath argument for alternative CVE source

pkg/inspector/image-inspector.go
This function uses the containers/<ID>/archive API instead of the now deprecated containers/<ID>/copy (used by the CopyFromContainer function).
=> Change to DownloadFromContainer

pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go
This will parse the response for errors and will attempt the next authentication configuration if an error is found.
To easily communicate the errors found a new channel is created and the go routines that handles the parsing and reporting will be started and destroyed for each authentication attempt.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1449742
=> parse daemon's response for errors

pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go
This will parse the response for errors and will attempt the next authentication configuration if an error is found.
To easily communicate the errors found a new channel is created and the go routines that handles the parsing and reporting will be started and destroyed for each authentication attempt.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1449742
Original Master PR: #42
=> [2.1] parse dockers daemon response for errors

cmd/image-inspector.go, pkg/cmd/types.go, pkg/imageserver/types.go, pkg/imageserver/webdav.go, pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_ginkgo_test.go, pkg/inspector/inspector_suite_test.go
this PR adds func checkAuth to image-inspector.go
checkAuth looks for an OAuth token on a request before calling the next http handler
currently it's only applied to the WebDAV content server
simple unit test added using ginkgo
=> add authorization check to webdav server 

pkg/imageserver/types.go, pkg/imageserver/webdav.go, pkg/inspector/image-inspector.go
Some times the value of DstPath is updated during the
inspection of the image. This will ensure it will be updated for the server.
=> Send "ServeImage" the location of the image contents

pkg/inspector/image-inspector.go
This fixes ~two~ one minor problems that can cause image-inspector to crush
1. If the scan fails then the results will still be sent to be parsed and this will cause a panic that will crush the software. Moved the parsing to only happen when the scan was successful.
2. ~When given the argument is appended with the name of the expected CVE file which is not the intent of this argument.~ I remembered that for this parameter that it is expected to be a path to be appended with "com.redhat.rhsa-RHEL7.ds.xml.bz2". (7 could be replaced with the RHEL version of the scanned image). I now feel that this will be a bit less convenient when providing entirely different cve files with custom checks. I just wanted to fix small bugs here so I removed this.
=> Openscap - Only parse reports when scan was successful

pkg/clamav/clamav_test.go, pkg/clamav/scanner.go, pkg/inspector/image-inspector.go
this PR adds a more useful error if initializing the ClamAV scanner fails. Currently if initializing fails, the user gets an error "unable to start clamd session" while information about the actual error (e.g. unable to connect to clamav socket) is lost. This change ensures the error will be bubbled up to the caller
=> return useful error on clamd initialization

pkg/cmd/types.go, pkg/imageserver/types.go, pkg/imageserver/webdav.go, pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_ginkgo_test.go
=> Code constants cleanup and refactoring

.travis.sh, .travis.yml, Dockerfile.travis, hack/install-tools.sh, pkg/imageserver/imageserver_suite_test.go, pkg/imageserver/webdav_test.go, pkg/inspector/image-inspector_integration_test.go, test/end-to-end/e2e.sh
This PR adds Integration tests will attempt to pull and scan an image without throwing an error. In order to accomplish this with our CI (travis), travis now runs tests inside a docker container (as travis does not support centos-based builds).
The PR also adds a set of integration tests for the WebDAV server (ensures http endpoints behave as expected).
the success of `docker build` will now also be tested by travis.
The additional tests are implemented with the [Ginkgo Test Framework](https://github.com/onsi/ginkgo). Ginkgo tests are compatible with `go test`
=> Add integration tests to Travis CI jobs

pkg/imageserver/webdav.go
The `syscall.Chroot` does  not change the current working directory, so that after the call '.' can be outside the tree rooted at '/'. In particular, the user can escape from a "chroot jail".
See `chroot(2)`, `openat(2)` manpages.
=> Change current working directory after chroot

cmd/image-inspector.go, pkg/api/types.go, pkg/clamav/clamav_test.go, pkg/clamav/scanner.go, pkg/cmd/types.go, pkg/cmd/types_test.go, pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go, pkg/openscap/openscap.go, pkg/openscap/openscap_test.go, vendor.conf, vendor/github.com/openshift/clam-scanner/pkg/clamav/session.go
As follow up of #55 I added the ability to scan existing containers. All options are applicable to the image (such as `-scan-type`, `-post-results-url` etc.) can be applied to the scanning of the container. 
```
$ ./image-inspector -container 37017548dc46 -scan-type clamav -clam-socket /var/run/clamd.scan/clamd.sock 
2017/07/19 14:47:49 Extracting image  to /var/tmp/image-inspector-434280052
2017/07/19 14:47:51 clamav scan took 0s (1 problems found)
```
=> Add option to scan for an existing container

pkg/openscap/openscap.go
It could fail to download the file but that doesn't mean that it will return an error from the function.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1459189
=> check that cve download status is OK

Dockerfile, cccp.yml
Fixes #88
Adds a file cccp.yml with `job-id: image-inspect`, needed to build
at registry.centos.org
=> Fix-88 Starts building image-inspector image at registry.centos.org

pkg/api/types.go, pkg/imageserver/webdav.go, pkg/inspector/image-inspector.go, pkg/inspector/image-inspector_test.go
When image-inspector fails to acquire an image and is in the serve mode it fails to serve this status and just exists. I consider this a bug.
To fix I added two fields to the metadata status: ImageAcquireSuccess, ImageAcquireError to report that status.
=> serve the status of image acquiring

pkg/openscap/openscap.go
Adds headers to the CVE file request under `getInputCVE` - Some servers require headers in order to supply a 200 response, in particular our default CVE host -`https://www.redhat.com/security/data/metrics/ds/`
BZ's: https://bugzilla.redhat.com/show_bug.cgi?id=1620376
https://bugzilla.redhat.com/show_bug.cgi?id=1620068
=> Add headers to request for CVE file
